name: nasa_backend
description: Backend for NASA project on Dart
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.2.0
  shelf_static: ^1.0.0
  http: ^1.2.2

dev_dependencies:
  lints: ^2.0.0
